/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ["class"],
    content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
    theme: {
        extend: {
            fontFamily: {
                display: ['Newsreader', 'serif'],
                body: ['Karla', 'sans-serif'],
                mono: ['Chivo Mono', 'monospace'],
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            colors: {
                cw: {
                    paper: '#F4F3ED',
                    canvas: '#FCFBFA',
                    masthead: '#EBE9E0',
                    ink: '#1C1E1A',
                    'ink-soft': '#5E635A',
                    'ink-mute': '#8A8F85',
                    fiduciary: '#1E3B2D',
                    'fiduciary-deep': '#11241B',
                    copper: '#A85B42',
                    'copper-soft': '#D8BCA4',
                    rule: '#D4D2C9',
                    'rule-soft': '#E3E1D6',
                    vetoed: '#8B2E2E',
                    'veto-bg': '#F2E6E6',
                    'veto-rule': '#D4A5A5',
                    'waiting-bg': '#EAE5D9',
                    'waiting-text': '#876538',
                    'waiting-rule': '#C7B9A3',
                    'approved-bg': '#E5EBE6',
                    'approved-rule': '#B0C4B6',
                    'archived-text': '#8A8F85',
                },
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
                popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
                primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
                secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
                muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
                accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
                destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
            },
            keyframes: {
                'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
                'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up':   'accordion-up 0.2s ease-out',
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
